{{- define "tenant.application.template" -}}
{{- `
{{- $sources := (ternary
  .sources
  (include "tenant.utils.list-or-map" (dict
    "value" .sources
    "propagateMapKeyToFields" (list "name" "ref")
    "priorityMapKey" "main"
  ) | fromYamlArray)
  (eq .sources nil)
) -}}
{{- range $sources -}}
  {{- if (ne .chart nil) -}}
    {{- $_ := unset . "ref" -}}
  {{- end -}}
{{- end -}}

{{ (dict
  "apiVersion" "argoproj.io/v1alpha1"
  "kind" "Application"
  "metadata" (dict
    "annotations" .annotations
    "finalizers" .finalizers
    "labels" .labels
    "name" .name
    "namespace" .namespace
  )
  "spec" (dict
    "destination" .destination
    "ignoreDifferences" .ignoreDifferences
    "info" (ternary
      .info
      (include "tenant.utils.list-or-map" (dict
        "value" .info
        "propagateMapKeyToFields" (list "name")
      ) | fromYamlArray)
      (eq .info nil)
    )
    "project" .project
    "revisionHistoryLimit" .revisionHistoryLimit
    "source" .source
    "sourceHydrator" .sourceHydrator
    "sources" $sources
    "syncPolicy" .syncPolicy
  )
) | toYaml }}
` | trim -}}
{{- end -}}

{{- range include "tenant.resources.applications" $ | fromYamlArray }}
---
{{ tpl (include "tenant.application.template" $) . | include "tenant.utils.post-render" }}
{{- end }}
