{{- define "tenant.application.template" -}}
{{- `
{{ (dict
  "apiVersion" "argoproj.io/v1alpha1"
  "kind" "Application"
  "metadata" (dict
    "annotations" .annotations
    "finalizers" .finalizers
    "labels" .labels
    "name" .name
    "namespace" .namespace
  )
  "spec" (dict
    "destination" .destination
    "ignoreDifferences" .ignoreDifferences
    "info" .info
    "project" .project
    "revisionHistoryLimit" .revisionHistoryLimit
    "source" .source
    "sourceHydrator" .sourceHydrator
    "sources" .sources
    "syncPolicy" .syncPolicy
  )
) | toYaml }}
` | trim -}}
{{- end -}}

{{- range include "tenant.resources.applications" $ | fromYamlArray }}
---
{{ tpl (include "tenant.application.template" $) . }}
{{- end }}
