{{- define "tenant.application.template" -}}
{{- `
{{ (dict
  "apiVersion" "argoproj.io/v1alpha1"
  "kind" "Application"
  "metadata" (dict
    "annotations" .annotations
    "finalizers" .finalizers
    "labels" .labels
    "name" .name
    "namespace" .namespace
  )
  "spec" (dict
    "destination" .destination
    "ignoreDifferences" .ignoreDifferences
    "info" (ternary
      .info
      (tpl "{{ template \"tenant.utils.list-or-map\" . }}" (dict
        "value" .info
        "propagateMapKeyToFields" (list "name")
      ) | fromYamlArray)
      (eq .info nil)
    )
    "project" .project
    "revisionHistoryLimit" .revisionHistoryLimit
    "source" .source
    "sourceHydrator" .sourceHydrator
    "sources" (ternary
      .sources
      (tpl "{{ template \"tenant.utils.list-or-map\" . }}" (dict
        "value" .sources
        "propagateMapKeyToFields" (list "name")
        "priorityMapKey" "main"
      ) | fromYamlArray)
      (eq .sources nil)
    )
    "syncPolicy" .syncPolicy
  )
) | toYaml }}
` | trim -}}
{{- end -}}

{{- range include "tenant.resources.applications" $ | fromYamlArray }}
---
{{ tpl (include "tenant.application.template" $) . | include "tenant.utils.post-render" }}
{{- end }}
