{{- define "resources.application-set.list" -}}
  {{- include "resources.list" (dict "root" $ "values" .Values.applicationSets "defaults" .Values.applicationSetDefaults) -}}
{{- end -}}

{{- range include "resources.application-set.list" $ | fromYamlArray }}
---
{{ include "resources.application-set.build" . }}
{{- end }}
