{{- define "resources-lib.application.list" -}}
  {{- include "resources-lib.list" (dict "root" $ "values" .Values.applications "defaults" .Values.applicationDefaults) -}}
{{- end -}}

{{- range include "resources-lib.application.list" $ | fromYamlArray }}
---
{{ include "resources-lib.application.build" . }}
{{- end }}
