{{- define "resources.application.list" -}}
  {{- include "resources.list" (dict "root" $ "values" .Values.applications "defaults" .Values.applicationDefaults) -}}
{{- end -}}

{{- range include "resources.application.list" $ | fromYamlArray }}
---
{{ include "resources.application.build" . }}
{{- end }}
