{{- define "resources.application.template" -}}
  {{- $.Files.Get "files/argoproj/application.yaml" -}}
{{- end -}}

{{- define "resources.application.build" -}}
  {{- $ := .root -}}
  {{- $data := .data -}}

  {{- tpl (include "resources.application.template" $) $data -}}
{{- end -}}

{{- define "resources.application.list" -}}
  {{- include "resources.list" (dict "root" $ "values" .Values.applications "defaults" .Values.applicationDefaults) -}}
{{- end -}}

{{- range include "resources.application.list" $ | fromYamlArray }}
---
{{ tpl (include "resources.application.template" $) . }}
{{- end }}
