{{- define "tenant.x-aplication-set.overrides" -}}
{{- $ := .root }}
{{- $appSet := .appSet }}

spec:
  goTemplate: true
  generators: []
  templatePatch: |
    {{ include "tenant.x-application-set.template-patch" (dict "root" $ "appSet" .) }}
{{- end -}}

{{- range include "tenant.resources.x-application-sets" $ | fromYamlArray }}
{{- $appSet := include "tenant.application-set.tpl" . | fromYaml }}
{{- $overrides := include "tenant.x-aplication-set.overrides" (dict "root" $ "appSet" .) | fromYaml }}
{{- /*{{- $_ := mustMergeOverwrite . (dict
  "goTemplate" true
  "generators" (include "tenant.x-application-set.generators" (dict "root" $ "appSet" .) | fromYamlArray)
  "templatePatch" (include "tenant.x-application-set.template-patch" (dict "root" $ "appSet" .))
) }} */ -}}
---
{{ mustMergeOverwrite $appSet $overrides | toYaml }}
{{- end }}
