{{- define "tenant.x-aplication-set.overrides" -}}
{{- $ := .root -}}
{{- $appSet := .appSet -}}

{{- $defaults := include "tenant.x-application-set.application-defaults" (dict "root" $ "appSet" $appSet) | fromYaml -}}
{{- $defaultEnabled := ne (index $defaults "$enabled") false -}}

{{- $generators := include "tenant.utils.list-or-map" (dict
  "value" $appSet.generators
) | fromYamlArray -}}
{{- $generators = include "tenant.x-application-set.x-git-generator.convert" $generators | fromYamlArray -}}

spec:
  goTemplate: true
  {{- with $generators }}
  generators:
    {{- range . }}
    - matrix:
        generators:
          - {{- . | toYaml | nindent 12 }}
          - list:
              elements:
                - enabled: {{ printf `{{ ternary (index . "$enabled") %t (hasKey . "$enabled") }}` $defaultEnabled | quote }}
      selector:
        matchExpressions:
          - key: enabled
            operator: NotIn
            values: ["false"]
    {{- end }}
  {{- else }}
  generators: []
  {{- end }}
  templatePatch: |
    {{- include "tenant.x-application-set.template-patch" (dict "root" $ "appSet" .) | nindent 4 }}
{{- end -}}

{{- range include "tenant.resources.x-application-sets" $ | fromYamlArray }}
{{- $appSet := include "tenant.application-set.tpl" . | fromYaml }}
{{- $overrides := include "tenant.x-aplication-set.overrides" (dict "root" $ "appSet" .) | fromYaml }}
---
{{ mustMergeOverwrite $appSet $overrides | toYaml }}
{{- end }}
