{{- define "resources.sealed-secret.template" -}}
{{- `
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .finalizers }}
  finalizers: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  {{- with .data }}
  data: {{ . }}
  {{- end }}
  {{- with .encryptedData }}
  encryptedData: {{- . | toYaml | nindent 4 }}
  {{- else }}
  encryptedData: {}
  {{- end }}
  {{- with .template }}
  template: {{- . | toYaml | nindent 4 }}
  {{- end }}
` -}}
{{- end -}}

{{- define "resources.sealed-secret.build" -}}
  {{- tpl (include "resources.sealed-secret.template" nil | trim) . -}}
{{- end -}}
