{{- range include "tenant.resources.role-bindings" $ | fromYamlArray }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
{{ template "tenant.metadata" (dict "data" .) }}
{{- if ne .roleRef nil }}
roleRef: {{ include "tenant.utils.to-yaml" (dict "value" .roleRef "indent" 2) }}
{{- end }}
{{- if and .subjectsObject .subjects }}
  {{- fail "Specify either 'subjectsObject' or 'subjects', not both." }}
{{- end }}
{{- $subjects := .subjects }}
{{- if ne .subjectsObject nil }}
  {{- $subjects = include "tenant.utils.map-to-list" (dict "map" .subjectsObject "field" "name") | fromYamlArray }}
{{- end }}
{{- if ne $subjects nil }}
subjects: {{ include "tenant.utils.to-yaml" (dict "value" $subjects "indent" 2) }}
{{- end }}
{{- end }}
