{{- range include "tenant.resources.roles" $ | fromYamlArray }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
{{ template "tenant.metadata" (dict "data" .) }}
{{- if and .rulesObject .rules }}
  {{- fail "Specify either 'rulesObject' or 'rules', not both." }}
{{- end }}
{{- with .rulesObject }}
{{- $rules := include "tenant.utils.map-to-list" (dict "map" .) | fromYamlArray }}
rules: {{ include "tenant.utils.to-yaml" (dict "value" $rules "indent" 2) }}
{{- else with .rules }}
rules: {{- . | toYaml | nindent 2 }}
{{- end }}
{{- end }}
