{{- range include "tenant.resources.role-bindings" $ | fromYamlArray }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
{{ template "tenant.metadata" (dict "data" .) }}
{{- with .roleRef }}
roleRef: {{- . | toYaml | nindent 2 }}
{{- end }}
{{- if and .subjectsObject .subjects }}
  {{- fail "Specify either 'subjectsObject' or 'subjects', not both." }}
{{- end }}
{{- with .subjectsObject }}
{{- $subjects := include "tenant.utils.map-to-list" (dict "map" . "field" "name") | fromYamlArray }}
subjects: {{ include "tenant.utils.to-yaml" (dict "value" $subjects "indent" 2) }}
{{- else with .subjects }}
subjects: {{- . | toYaml | nindent 2 }}
{{- end }}
{{- end }}
