apiVersion: v2
name: resources
description: A Helm chart for creating Kubernetes resources
type: application
version: 0.1.0
dependencies:
  - name: resources-lib
    version: 0.1.0
    repository: file://../resources-lib
