defaults: {}

# Argo - AppProject
appProjectDefaults: {}
appPojects: {}

# Argo - Application
applicationDefaults: {}
applications: {}

# Argo - ApplicationSet
applicationSetDefaults:
  template:
    metadata: {}
    spec:
      destination: {}
      project: default
applicationSets: {}

# Bitnami - SealedSecret
sealedSecretDefaults: {}
sealedSecrets: {}

# Core - LimitRange
limitRangeDefaults: {}
limitRanges: {}

# Core - Namespace
namespaceDefaults: {}
namespaces: {}

# Core - ResourceQuota
resourceQuotaDefaults: {}
resourceQuotas: {}

# Networking - NetworkPolicy
networkPolicyDefaults: {}
networkPolicies: {}

# RBAC - ClusterRoleBinding
clusterRoleBindingDefaults: {}
clusterRoleBindings: {}

# RBAC - ClusterRole
clusterRoleDefaults: {}
clusterRoles: {}

# RBAC - RoleBinding
roleBindingDefaults: {}
roleBindings: {}

# RBAC - Role
roleDefaults: {}
roles: {}

# Extra Resources
extraResources: {}
