groups:
  gitlab-runner:
    namespaceDefaults:
      name: "gitlab-runner-{{.id}}"
    namespaces:
      foo: {}
      bar: {}
      baz: {}

namespaces:
  gitlab-runner-foo: {}
  gitlab-runner-bar: {}
  gitlab-runner-baz: {}

  jenkins-agent-foo: {}
  jenkins-agent-bar: {}
  jenkins-agent-baz: {}
