defaults: {}

applicationDefaults:
  annotations:
    is-cool: "true"

xApplicationSetDefaults:
  generators:
    - x-git:
        repoURL: bob.com
        directories:
          - path: "{{.name}}"
        valueFiles:
          - values.yaml

xApplicationSets:
  foo: {}
