defaults: {}

applicationDefaults: {}
application: ~
applications: {}

applicationSetDefaults: {}
applicationSet: ~
applicationSets: {}

projectDefaults: {}
project: ~
projects: {}

clusterRoleBindingDefaults: {}
clusterRoleBinding: ~
clusterRoleBindings: {}

clusterRoleDefaults: {}
clusterRole: ~
clusterRoles: {}

limitRangeDefaults: {}
limitRange: ~
limitRanges: {}

namespaceDefaults: {}
namespace: ~
namespaces: {}

networkPolicyDefaults: {}
networkPolicy: ~
networkPolicies: {}

resourceQuotaDefaults: {}
resourceQuota: ~
resourceQuotas: {}

roleBindingDefaults: {}
roleBinding: ~
roleBindings: {}

roleDefaults: {}
role: ~
roles: {}

sealedSecretDefaults: {}
sealedSecret: ~
sealedSecrets: {}

xApplicationSetDefaults: {}
xApplicationSet: ~
xApplicationSets: {}

extraResources: {}
