# TODO:
#   * Remove "variable fields" :'(
#     * Breaks extra resources

applicationDefaults:
  annotations:
    my-name-is: "{{.name}}"
  sources:
    main:
      repoURL: github.com
      chart: google
    values:
      repoURL: google.com
    extras:
      $enabled: false
      repoURL: foo.com
      ref: xtras

xApplicationSet:
#   $enabled: false
  name: test
  template:
    spec:
      project: default
      info:
        - name: food
          value: pizza
  generators:
    - list:
        elements:
          - name: foo
            info:
              - name: food
                value: pizza
          - name: bar
            info:
              food:
                # name: food
                value: pizza
              age:
                $enabled: false
                value: "12"
              repoURL:
                value: https://google.com
          - name: baz
            sources:
              extras:
                $enabled: true
          - id: cat
            name: "app-{{ `{{.id}}` }}"
            annotations:
              food: ~
            sources:
              - repoURL: gogs.com
                name: ~

# applicationDefaults:
#   annotations:
#     name: ~
#   info:
#     food:
#       value: pizza
#   sources:
#     main:
#       repoURL: github.com
#       chart: google
#     values:
#       repoURL: google.com
#     extras:
#       # $enabled: false
#       repoURL: foo.com
#       ref: xtras
# 
# applications:
#   foo: {}
#   bar: {}
