roleBindingDefaults: {}

roleBindings:
  foo:
    roleRef:
      kind: Role
      name: pod-reader
      apiGroup: rbac.authorization.k8s.io
    subjectsObject:
      jane:
        kind: User
        name: bob
        apiGroup: rbac.authorization.k8s.io
