{{- range include "tenant.resources.sealed-secrets" $ | fromYamlArray }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
{{ template "tenant.metadata" (dict "data" .) }}
spec:
  {{- with .data }}
  data: {{ include "tenant.field.multi-line-string" (dict "value" . "indent" 4) }}
  {{- end }}
  {{- with .encryptedData }}
  encryptedData: {{- . | toYaml | nindent 4 }}
  {{- else }}
  encryptedData: {}
  {{- end }}
  {{- with .template }}
  template: {{- . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
