{{- define "resources-lib.limit-range.template" -}}
{{- `
apiVersion: v1
kind: LimitRange
metadata:
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .finalizers }}
  finalizers: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  {{- if and .limitsObject .limits }}
    {{- fail "Specify either 'limitsObject' or 'limits', not both."}}
  {{- end }}
  {{- with .limitsObject }}
  {{- $limits := include "resources-lib.utils.map-to-list" (dict "map" .) | fromYamlArray }}
  limits: {{ include "resources-lib.utils.render-object" (dict "value" $limits "indent" 4) }}
  {{- else with .limits }}
  limits: {{- . | toYaml | nindent 4 }}
  {{- else }}
  limits: []
  {{- end }}
` -}}
{{- end -}}

{{- define "resources-lib.limit-range.build" -}}
  {{- tpl (include "resources-lib.limit-range.template" nil | trim) . -}}
{{- end -}}
