{{- range include "tenant.resources.limit-ranges" $ | fromYamlArray }}
---
apiVersion: v1
kind: LimitRange
metadata:
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .finalizers }}
  finalizers: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  {{- if and .limitsObject .limits }}
    {{- fail "Specify either 'limitsObject' or 'limits', not both."}}
  {{- end }}
  {{- with .limitsObject }}
  {{- $limits := include "tenant.utils.map-to-list" (dict "map" .) | fromYamlArray }}
  limits: {{ include "tenant.utils.to-yaml" (dict "value" $limits "indent" 4) }}
  {{- else with .limits }}
  limits: {{- . | toYaml | nindent 4 }}
  {{- else }}
  limits: []
  {{- end }}
{{- end }}
