{{- range include "tenant.resources.resource-quotas" $ | fromYamlArray }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .finalizers }}
  finalizers: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  {{- with .hard | include "tenant.utils.filter-map" | fromYaml }}
  hard: {{- . | toYaml | nindent 4 }}
  {{- else }}
  hard: {}
  {{- end }}
  {{- with .scopeSelector }}
  scopeSelector: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .scopes }}
  scopes: {{- . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
