{{- range include "resources.list" (dict
  "root" $
  "values" .Values.xApplicationSets
  "defaults" .Values.xApplicationSetDefaults
) | fromYamlArray }}
{{- $_ := set . "goTemplate" true }}
{{- $_ := set . "generators" (include "tenant.application-set.generators" (dict "root" $ "appSet" .) | fromYamlArray) }}
{{- $_ := unset . "generatorsObject" }}
{{- $_ := set . "templatePatch" (include "tenant.application.template" (dict "root" $ "appSet" .)) }}
---
{{ tpl (include "resources.application-set.template" $) . }}
{{- end }}
