{{- range $id, $_ := .Values.applications -}}
{{- with include "tenant.resource.data" (dict "root" $ "id" $id "data" . "defaults" $.Values.applicationDefaults) | fromYaml }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ tpl (include "tenant.application.template" $) . }}
{{- end }}
{{- end -}}
