{{- range $id, $_ := .Values.applications -}}
{{- with include "build-resource-data" (dict "root" $ "id" $id "data" . "defaults" $.Values.applicationSetDefaults) | fromYaml }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ tpl (include "application-template" $) . }}
{{- end }}
{{- end -}}
