{{- range include "tenant.resources.applications" $ | fromYamlArray }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ tpl (include "tenant.application.template" (dict "root" $)) . }}
{{- end }}
