{{- range include "tenant.resource.list" (dict "root" $ "values" .Values.projects "defaults" .Values.projectDefaults) | fromYamlArray }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
  {{- with .finalizers }}
  finalizers: {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- if ne .permitOnlyProjectScopedClusters nil }}
  permitOnlyProjectScopedClusters: {{ .permitOnlyProjectScopedClusters }}
  {{- end }}
  {{- with .description }}
  description: {{ . | quote }}
  {{- end }}
  {{- with .sourceRepos }}
  sourceRepos: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .destinationsObject }}
  destinations:
    {{- range $id, $_ := . }}
    {{- $_ := set . "namespace" (.namespace | default $id) }}
    {{- if and (eq .name nil) (eq .server nil) }}
      {{- $_ := set . "name" "in-cluster" }}
    {{- end }}
    - {{ . | toYaml | indent 6 | trim }}
    {{- end }}
  {{- else with .destinations }}
  destinations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .clusterResourceWhitelistObject | default dict | dict "map" | include "tenant.utils.map-to-list" | fromYamlArray }}
  clusterResourceWhitelist: {{- . | toYaml | nindent 4 }}
  {{- else with .clusterResourceWhitelist }}
  clusterResourceWhitelist: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .clusterResourceBlacklistObject | default dict | dict "map" | include "tenant.utils.map-to-list" | fromYamlArray }}
  clusterResourceBlacklist: {{- . | toYaml | nindent 4 }}
  {{- else with .clusterResourceBlacklist }}
  clusterResourceBlacklist: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .namespaceResourceBlacklistObject | default dict | dict "map" | include "tenant.utils.map-to-list" | fromYamlArray }}
  namespaceResourceBlacklist: {{- . | toYaml | nindent 4 }}
  {{- else with .namespaceResourceBlacklist }}
  namespaceResourceBlacklist: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .namespaceResourceWhitelistObject | default dict | dict "map" | include "tenant.utils.map-to-list" | fromYamlArray }}
  namespaceResourceWhitelist: {{- . | toYaml | nindent 4 }}
  {{- else with .namespaceResourceWhitelist }}
  namespaceResourceWhitelist: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .orphanedResources }}
  orphanedResources: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with include "tenant.utils.map-to-list" (dict "map" (.rolesObject | default dict) "field" "name") | fromYamlArray }}
  roles: {{- . | toYaml | nindent 4 }}
  {{- else with .roles }}
  roles: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .syncWindows }}
  syncWindows: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .signatureKeys }}
  signatureKeys: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .sourceNamespaces }}
  sourceNamespaces: {{- . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
