{{- range include "tenant.resource.list-with-namespaced" (dict
  "root" $
  "key" "networkPolicies"
  "defaults" $.Values.networkPolicyDefaults
) | fromYamlArray }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .finalizers }}
  finalizers: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  {{- with .egress }}
  egress: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .ingress }}
  ingress: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- if ne .podSelector nil }}
  podSelector: {{ ternary "{}" (.podSelector | toYaml | nindent 4) (empty .podSelector) }}
  {{- end }}
  {{- with .policyTypes }}
  policyTypes: {{- . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
