{{- range include "tenant.resource.list-with-namespaced" (dict
  "root" $
  "key" "resourceQuotas"
  "defaults" $.Values.resourceQuotaDefaults
) | fromYamlArray }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .finalizers }}
  finalizers: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  {{- with .hard }}
  hard: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .scopeSelector }}
  scopeSelector: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .scopes }}
  scopes: {{- . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
