{{- range include "tenant.resource.list-with-namespaced" (dict
  "root" $
  "key" "roleBindings"
  "defaults" $.Values.roleBindingDefaults
) | fromYamlArray }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .finalizers }}
  finalizers: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
{{- with .roleRef }}
roleRef: {{- . | toYaml | nindent 2 }}
{{- end }}

{{- if and .subjectsObject .subjects }}
  {{- fail "Specify either `subjectsObject` or `subjects`, not both." }}
{{- end }}
{{- with .subjectsObject }}
subjects:
  {{- range $key, $val := . }}
    {{- $_ := set . "name" (.name | default $key) }}
    {{- . | toYaml | nindent 2 }}
  {{- end }}
{{- else with .subjects }}
subjects: {{- . | toYaml | nindent 2 }}
{{- end }}
{{- end }}
