{{- define "tenant.field" -}}
  {{- $field := .field -}}
  {{- $value := .value -}}
  {{- $indent := .indent | default 0 -}}

  {{- if ne $value nil -}}
    {{- (dict $field $value) | toYaml | nindent $indent -}}
  {{- end -}}
{{- end -}}

{{- range include "tenant.resources.sealed-secrets" $ | fromYamlArray }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
{{ template "tenant.metadata" (dict "data" .) }}
spec:
  {{- include "tenant.field" (dict
    "field" "data"
    "value" .data
    "indent" 2
  ) }}
  {{- include "tenant.field" (dict
    "field" "encryptedData"
    "value" .encryptedData
    "indent" 2
  ) }}
  {{- include "tenant.field" (dict
    "field" "template"
    "value" .template
    "indent" 2
  ) }}
{{- end }}
