{{- /*
  The below nested-template is a best-effort implementation of the Helm `tpl` function (which is not available for ApplicationSets).

  The below nested-template accepts an input dictionary with the following fields:
    `template` - A string template, e.g. "Hello {{.name}}"
    `data` - A map (dict) of data to evaluate the template using, e.g. {"name": "Bob"}
    `out` - An output map (dict), allowing the evaluated template to be captured. A `value` field will be populated.

  If https://github.com/argoproj/argo-cd/pull/26614 gets merged, the `tpl` function can be used instead.
*/ -}}
{{- define "tpl" -}}
  {{- /* Extract arguments */ -}}
  {{- $template := .template -}}
  {{- $data := .data -}}
  {{- $out := .out -}}

  {{- /* Find everything that looks like a template, e.g. "{{.name}}", and loop over each of them */ -}}
  {{- range $match := regexFindAll "{{ *\\..*? *}}" $template -1 -}}
    {{- /* Extract all of the keys from the match, e.g: "{{.foo.bar}}" -> ["foo", "bar"] */ -}}
    {{- $keys := $match | substr 2 (int (sub (len $match) 2)) | trim | substr 1 -1 | splitList "." -}}

    {{- /* Traverse the application data, using the match's keys. If a value is not found, an empty string is used. */ -}}
    {{- /* We can't use the sprig `dig` function as it doesn't accept a dynamic list of values. */ -}}
    {{- $obj := $data -}}
    {{- range $key := $keys -}}
      {{- /* If the current object isn't a map, abort as we can't traverse any further */ -}}
      {{- if ne (kindOf $obj) "map" -}}
        {{- $obj = "" -}}
        {{- break -}}
      {{- end -}}

      {{- /* Update the object to use the value of the current key. After the last iteration, `$obj` will contain the final value */ -}}
      {{- $obj = get $obj $key -}}
    {{- end -}}

    {{- /* Replace the "match" (e.g. "{{.name}}") in the template with the digged value */ -}}
    {{- $template = replace $match (toString $obj) $template -}}
  {{- end -}}

  {{- $_ := set $out "value" $template -}}
{{- end -}}

{{- block "template-name-first" . -}}
  {{- $out := dict -}}
  {{- template "tpl" (dict "template" .name "data" . "out" $out) -}}
  {{- $_ := set . "name" $out.value -}}
{{- end -}}

{{- block "template-self" . -}}
  {{- $out := dict -}}
  {{- template "tpl" (dict "template" (. | toYaml) "data" . "out" $out) -}}
  {{- $newData := $out.value | fromYaml -}}

  {{- range $key, $val := $newData -}}
    {{- $_ := set $ $key $val -}}
  {{- end -}}
{{- end -}}

{{- $ := . -}}
metadata:
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end -}}
  {{- with .finalizers }}
  finalizers: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- with .destination }}
  destination: {{- . | toYaml | nindent 4 }}
  {{- end -}}
  {{- with .ignoreDifferences }}
  ignoreDifferences: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- if and .infoObject .info }}
    {{- fail "Specify either `infoObject` or `info`, not both." }}
  {{- end }}
  {{- with .infoObject }}
  info:
    {{- range $key, $val := . }}
    - name: {{ $key | snakecase | replace "_" " " | title }}
      value: {{ $val }}
    {{- end }}
  {{- else with .info }}
  info: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .project }}
  project: {{ . }}
  {{- end -}}
  {{- if ne .revisionHistoryLimit nil }}
  revisionHistoryLimit: {{ .revisionHistoryLimit }}
  {{- end }}
  {{- with .source }}
  source: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .sourceHydrator }}
  sourceHydrator: {{- . | toYaml | nindent 4}}
  {{- end }}
  {{- if and .sourcesObject .sources }}
    {{- fail "Specify either `sourcesObject` or `sources`, not both." }}
  {{- end }}
  {{- with .sourcesObject }}
  sources:
    {{- $mainSourceKey := "main" }}
    {{- $sourcesList := list (pick . $mainSourceKey) (omit . $mainSourceKey) }}
    {{- range $sourcesList }}
    {{- range $sourceId, $_ := . }}
    {{- if or (eq . nil) (eq .enabled false) -}}
      {{- continue -}}
    {{- end -}}
    {{- if and (eq .ref nil) (eq .chart nil) }}
      {{- $_ := set . "ref" $sourceId }}
    {{- end }}
    {{- $_ := set . "name" (.name | default $sourceId) }}
    - {{ . | toYaml | nindent 6 | trim }}
    {{- end }}
    {{- end }}
  {{- else with .sources }}
  sources: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .syncPolicy }}
    {{- with .syncOptionsObject }}
      {{- $syncOptions := list }}
      {{- range $key, $val := . }}
        {{- $syncOptions = append $syncOptions (printf "%s=%s" (title $key) (toString $val)) }}
      {{- end }}
      {{- $_ := unset $.syncPolicy "syncOptionsObject" }}
      {{- $_ := set $.syncPolicy "syncOptions" $syncOptions }}
    {{- end }}
  syncPolicy: {{- . | toYaml | nindent 4 }}
  {{- end }}
